# This is a basic workflow to help you get started with Actions

name: random delimeters

# Controls when the workflow will run
on:
  push:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  bash:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Set the value in bash
        id: step_one
        run: |
          EOF=$(dd if=/dev/urandom bs=15 count=1 status=none | base64)
          echo "JSON_RESPONSE<<$EOF" >> $GITHUB_ENV
          curl https://example.com >> $GITHUB_ENV
          echo "$EOF" >> $GITHUB_ENV
      - run: echo $JSON_RESPONSE
      
  pwsh:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Set the value in pwsh
        id: step_one
        run: |
          -join (1..15 | ForEach {[char]((48..57)+(65..90)+(97..122) | Get-Random)}) | set EOF
          "JSON_RESPONSE<<$EOF" >> $env:GITHUB_ENV
          (Invoke-WebRequest -Uri "https://example.com").Content >> $env:GITHUB_ENV
          "$EOF" >> $env:GITHUB_ENV
      - run: echo $env:JSON_RESPONSE
