name: Call a reusable workflow and use its outputs

on:
  workflow_dispatch:
  push:

jobs:
  job1:
    uses: ./.github/workflows/reusable-workflow.yml

  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - run: echo ${{ needs.job1.outputs.firstword }} ${{ needs.job1.outputs.secondword }}
      - name: Dump jobs context from reusable workflow
        run: echo ${{ needs.job1.outputs.jobscontext }}
