name: Call a reusable workflow

on:
  pull_request:

jobs:

  call-workflow-passing-data:
    permissions:
      contents: read
      pull-requests: write
    uses: lucascosti/actions-public-playground/.github/workflows/reusable-workflow.yml@31312_reusable_workflow_changes
    with:
      config-path: .github/labeler.yml
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
