name: Artifact download

on: [workflow_dispatch]

jobs:
  download:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/download-artifact@v3
        with:
          name: Test artifact
      - run: |
          ls
          cat thefile.txt
