name: Generate random failure
on: push
jobs:
  randomly-failing-job:
    runs-on: ubuntu-latest
    steps:
      - id: checkout
        uses: actions/checkout@v2
      - name: Generate 0 or 1
        id: generate_number
        run:  echo "::set-output name=random_number::$(($RANDOM % 2))" 
      - name: Make tacos
        run: |
          if [[ ${{ steps.generate_number.outputs.random_number }} == 0 ]]; then; return 0
          else; return 1; fi
      - name: dump context
        run: echo '${{ toJSON(steps) }}' 
