name: Reusable deploy workflow
on:
  workflow_call:
    inputs:
      build_id:
        required: true
        type: number
      deploy_target:
        required: true
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy build to target
        run: echo "deploy --build ${{ inputs.build_id }} --target ${{ inputs.deploy_target }}
        
