name: Build
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build with set
        run: |
          echo Hi Mum
          exit 1
  
  debug:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Dump needs context
        run: echo '${{ toJSON(needs) }}'
