name: Redis service container
on: push
jobs:
  redis-job:
    runs-on: ubuntu-latest
    services:
      redis:
        image: mysql
        ports:
          # Maps port 5200 in the service container to port 5432 on the Docker host.
          - 5432:5200
    steps:
      - run: echo '${{ toJSON(job) }}'
      - run: mysqladmin -h localhost -P 5432 ping 
      - run: echo '${{ toJSON(job) }}' 
