name: Build
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      build_id: ${{ steps.build_step.outputs.build_id }}
    steps:
      - name: Build
        id: build_step
        run: |
          # ./build
          echo "::set-output name=build_id::ABC123" 
      - name: Dump strategy context
        run: echo '${{ toJSON(strategy) }}'
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Dump needs context
        run: echo ${{ needs.build.outputs.build_id }}
      - name: Dump strategy context
        run: echo '${{ toJSON(strategy) }}'
        
  debug:
    needs: [build, deploy]
    runs-on: ubuntu-latest
    steps:
      - name: Dump strategy context
        run: echo '${{ toJSON(strategy) }}'
