
name: Pull request workflow (on PR branch)
on:
 - push
jobs:
  run_me:
    # Job name is Greeting
    name: Dump context
    # This job runs on Linux
    runs-on: ubuntu-latest
    steps:
      - name: Dump github context payload
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Run if label present
        run: |
          echo "${{ !contains(github.event.pull_request.labels.*.name, 'sync-english-index-for-') }}"
          echo "${{ !contains(github.event.pull_request.labels.*.name, 'docs-') }}"
