name: Pull request workflow
on:
 - pull_request
 - pull_request_target
 - pull_request_review
 - pull_request_review_comment
jobs:
  run_me:
    # Job name is Greeting
    name: Dump context
    # This job runs on Linux
    runs-on: ubuntu-latest
    steps:
      - name: Dump github context payload
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Check expression against labels
        run: |
          echo "Match sync-english-index-for- : ${{ contains(fromJSON(github.event.pull_request.labels.*.name), 'sync-english-index-for-') }}"
          echo "Match docs- : ${{ contains(fromJSON(github.event.pull_request.labels.*.name), 'docs-') }}"
          echo "Match bug: ${{ contains(fromJSON(github.event.pull_request.labels.*.name), 'bug') }}"
          echo 'The labels object ${{ fromJSON(github.event.pull_request.labels.*.name) }}'

        
