name: Pull request workflow
on:
 - pull_request
 - pull_request_target
 - pull_request_review
 - pull_request_review_comment
jobs:
  run_me:
    # Job name is Greeting
    name: Dump context
    # This job runs on Linux
    runs-on: ubuntu-latest
    steps:
      - name: Dump github context payload
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
        
