name: Release test
on:
  release:
    types:
     - prereleased
     - released
     - published

jobs:
  release_test:
    runs-on: ubuntu-latest
    steps:
      - run: echo This job was triggered by a release
