
name: Trigger on tag
on:
  push:
    branches:
      - nothing
    tags:
      - run_workflow*
jobs:
  tag_test:
    name: Tag test
    # This job runs on Linux
    runs-on: ubuntu-latest
    steps:
      - run: echo this was triggered from a tag push
